apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-2204-debug
spec:
  replicas: 2
  template:
    spec:
      initContainers:
      - name: substitute-env
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            envsubst < /tmp/.env > /tmp/.env;
        envFrom:
          - secretRef:
              name: onplus-dev-api
        volumeMounts:
          - name: configmap-onplus-dev-api
            mountPath: /tmp/.env
            subPath: .env
            readOnly: false

      containers:
        - name: ubuntu
          volumeMounts:
          - name: configmap-onplus-dev-api
            mountPath: /tmp/.env
            subPath: .env

          envFrom:
            - secretRef:
                name: onplus-dev-api
      volumes:
        - name: configmap-onplus-dev-api
          configMap:
            name: onplus-dev-api
        - name: onplus-dev-api
          secret:
            defaultMode: 420
            secretName: secret-dev