apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onplus

configMapGenerator:
- name: onplus-dev-api
  files:
  - .env

resources:
- ../../base

patches:
- path: deployment-dev.yaml